name: eksperimen_sml_mirza_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - mlflow==2.14.1  
    - dagshub
    - virtualenv